![logos_cursopython.png]()

# Introducción al Python Científico orientado al procesamiento de datos hidrometeorológicos

Contenidos

* ¿Qué es Python?
* Introducción a Python Científico
  * Tipos de Datos
  * Asignación de Variables y Operaciones Aritméticas
  * Funciones Matemáticas definidas en Python
  * Listas, tuplas y diccionarios
  * Operadores para comparar
  * Estructuras Lógicas IF
  * Funciones
  * Operadores Lógicos AND, OR, IN, NOT IN
  * Ejercicios
* Numpy
  * Indexado de los array de Numpy
  * Operaciones sobre arrays
  * Ejercicios
* Pandas
  * Series
  * Cómo extraemos información de una serie?
  * DataFrames
  * Datos faltantes y relleno
  * Operaciones sobre un DataFrame
  * Unir y concatenar DataFrames
  * DateTime de Pandas
  * Ejercicios
* Matplotlib
  * Grafico simple
  * Múltiples gráficos
  * Estilos personalizados para graficar en Matplotlib
  * Otros tipos de graficos
  * Guardado de una figura
  * Ejercicios
* Actividad

# Autores: Ing. Rocío Otero y Lic. Matías E. Suárez
*Contactos: rocio.otero@mi.unc.edu.ar y matias.suarez@unc.edu.ar*

##¿Qué es Python?

Python es un lenguaje de alto nivel de programación intrpretado cuya filosofía hace hincapié en la legibilidad de su código, se utiliza para desarrollar aplicaciones de todo tipo, ejemplos: Instagram, Netflix, Spotify, Panda3D, entre otros.​

Se trata de un lenguaje de programación multiparadigma, ya que soporta parcialmente la orientación a objetos, programación imperativa y, en menor medida, programación funcional. Es un lenguaje interpretado, dinámico y multiplataforma.

Administrado por Python Software Foundation, posee una licencia de código abierto, denominada Python Software Foundation License. Python se clasifica constantemente como uno de los lenguajes de programación más populares.

**¿Cómo se usa Python?**

Hay muchas maneras de usar el lenguaje Python. Una forma muy útil y conocida (pero no la única) es usar los Notebooks de Jupyter, el cual es un entorno web para computación interactiva.

Podemos crear y editar "celdas" de código Python que podés editar y volver a ejecutar, podés intercalar celdas de texto, fórmulas matemáticas, y hacer que gráficos se muestren inscrutados en la misma pantalla. Estos archivos se guardan con extensión *.ipynb*, que pueden exportarse a diversos formatos estátucos como html o como código python puro. (.py)

Los notebooks son muy útiles para la **"programación exploratoria"**, muy frecuente en ciencia e ingeniería

Todo el material de estos cursos estarán en formato notebook.

Para ejecutar IPython Notebook, desde una terminal tipear:


**Programas**

También podemos usar Python para hacer programas o scripts.
Esto es, escribir nuestro código en un archivo con extensión `.py` y ejecutarlo con el intérprete de python.  
Por ejemplo, podemos crear un archivo llamado hello.py (al que se le llama módulo) que tenga este contenido:

```python
    print("¡Hola curso!")
```

Si ejecutamos **python hello.py** en una terminal se ejecutará en el interprete Python y obtendremos el resultado.

Modo de uso:
* Local (Windos y Linux): Es necesario instalar Anaconda.
* En línea: No es necesario instalar nada. Se utiliza con la herramiento Google Colab del Drive.

##Introducción a Python Científico

### Tipos de Datos

**Algunos tipos de datos básicos en Python:**

int  -> para números enteros (ejemplo: 2)

float  -> para números reales (ejemplo: 3.5)

str -> lista de caracteres, para texto, nombres de archivos  (ejemplo: "Hola Mundo", hay que escribir entre " o entre ')

In [ ]:
print(2) # print() es una función de python que imprime en pantalla
print(type(2)) # Con type() imprimimos el tipo de dato

In [ ]:
print(3.5)
print(type(3.5)) # lo que se escribe luego de # es comentario, no se ejecuta en el código

In [ ]:
print('Imagen1.png')
# Ejercicio: imprimir también el tipo de dato

### Asignación de Variables y Operaciones Aritméticas

Las operaciones aritméticas básicas son:

* adición: `+`
* sustracción: `-`
* multiplicación: `*`
* división: `/`
* módulo (resto de división): `%`  
* potencia: `**`
* división entera: `//`

**Asignación de variables en python**

In [ ]:
x = 189  # x es una variable con valor 189, tipo de la variable: int (entero)
print(x, type(x)) # Imprimimos en pantalla el valor de x y su tipo

**Asignación de variables en notación científica**

In [ ]:
x_c = 10e-5
print(x_c)
print("El tipo de dato asignado con notación científica es ",type(x_c))

In [ ]:
# Se pueden hacer asignaciones simultáneas:
nro_1, nro_2, nro_3, nro_4 , var = 0.348, -10.5, 1.5e2, 5, "hola"

print (nro_1, type(nro_1))
print (nro_2, type(nro_2))
print (nro_3, type(nro_3))
print (nro_4, type(nro_4))
print (var, type(var))

**Es posible convertir tipos de datos numéricos con las funciones int(), float(), complex()**

In [ ]:
a = 3.2 # a es real (flotante)
print(a, type(a))

# Lo convertimos a entero de esta manera
a = int(a)
print(a, type(a))

# Notar que el numéro se redondeo al entero más cercano

**Es posible convertir tipos de datos numéricos con las funciones int(), float(), complex()**

In [ ]:
a = 3.2 # a es real (flotante)
print(a, type(a))

# Lo convertimos a string de esta manera
a = str(a)
print(a, type(a))

print('a ya no es más un flotante. Podemos verificarlo tratando de realizar una suma.')

In [ ]:
# print(a+2)

# Como resultado obtendremos un error que nos dice que estamos tratando de concatenar
# un string con un numero. Es decir, python no sabe que hacer cuando le pedimos que
# sume unas letras (string) a un numero.

In [ ]:
x = 1.32

resultado = ((21.2 + 4.5)**0.2 / x) + 1

print(resultado)

### Funciones Matemáticas definidas en python

Hay más funciones y constantes definidas en modulos. Los más conocidos son *math* y *numpy*

Para utilizarlos debemos importarlos. Esto se hace de la siguiente manera:


*   import math
*   import numpy as np

In [ ]:
import math
import numpy as np

In [ ]:
# Algunas de las funciones que trae el modulo math son las siguientes:

print(round(5.6777, 3)) # funcion que redondea el numero 5.6777 en el decimal 3
print(math.factorial(5))  # Calculo el factorial
print(math.sqrt(16))  # Calculo la raiz cuadrada

In [ ]:
# Algunas de las funciones que trae el modulo numpy son las siguientes:

print(np.pi) # Imprimo la constante pi
print(np.sqrt(25)) # Raiz cuadrada de 25
print(np.sin(np.pi/2)) # sen(pi)
print(np.exp(1)) # exp(1)

### Datos booleanos o logical (True y False)

Son variables que solo pueden tomar dos posible valores: True (verdadero) o False (Falso)

Notar que están definidas con la primer letra en mayuscula!

In [ ]:
var1 = True # el valor verdadero: True
var2 = False # el valor falso: False

print(var1, type(var1))
print(var2, type(var2))

### Listas, tuplas y diccionarios

Las listas y tuplas son secuencias de numeros o strings. **LA DIFERENCIA** es que las **listas son mutables**. Es decir, es un objeto que puede cambiar: extenderse con otra secuencia, agregar o quitar elementos, cambiar un elemento o una porción por otra, reordenarse *in place*, etc.  

Los diccionarios son otro tipo de estructuras de alto nivel que ya vienen incorporados. A diferencia de las secuencias, los valores **no están en una posición** sino bajo **una clave**: son asociaciones `clave:valor`

### **Listas**

In [ ]:
# Ejemplo de lista

lista_ejemplo = [1,2,-1,0,'hola']

print(type(lista_ejemplo))

# Podemos ver los elementos que hay en cada posición
print(lista_ejemplo[0]) # 0 es la primera posición
print(lista_ejemplo[-1]) # -1 es la ultima posición

### **Tuplas**

In [ ]:
# Ejemplo de tupla

tupla_ejemplo = (1,2,-1,0,'hola')

print(type(tupla_ejemplo))

# Podemos ver los elementos que hay en cada posición
print(tupla_ejemplo[0]) # 0 es la primera posición
print(tupla_ejemplo[-1]) # -1 es la ultima posición

In [ ]:
# Es posible modificar el valor de un elemento de la lista
# Por ejemplo cambio el valor del primer elemento por 10
lista_ejemplo[0] = 10

print(lista_ejemplo)

In [ ]:
# NO es posible modificar el valor de un elemento de una tupla
# Por ejemplo intento cambiar el valor del primer elemento por 10
# tupla_ejemplo[0] = 10

print(tupla_ejemplo)

### **Diccionarios**

In [ ]:
# Ejemplo de un diccionario

dict_ejemplo = {'Estacion1':1, 'Estacion2':5, 'Estacion3':10, 'Estacion4':'SinDato'}

# Estacion1, Estacion2, Estacion3 y Estacion4 son las claves del diccionario
# 1, 5, 10 y 'SinDato' son los valores asociados

# Visualizamos que hay en la clave 'Estacion2'
print(dict_ejemplo['Estacion2'])

In [ ]:
# Es posible visualizar todas las claves del diccionario

dict_ejemplo.keys()

Los diccionarios **son mutables**. Es decir, podemos cambiar el valor de una clave, agregar o quitar.  

Podemos definir un diccionario dentro de otro diccionario.

In [ ]:
# diccionario dentro de otro diccionario

dict_ejemplo2 = {'Clave1':1, 'Clave2':dict_ejemplo, 'Clave3':10, 'Clave4':{'Subclave1':1}}

print(dict_ejemplo2.keys())

In [ ]:
# Verificamos que hay en la Clave2

dict_ejemplo2['Clave2']

# Vemos que dentro de Clave2 está el diccionario dict_ejemplo definido anteriormente

### Operadores para comparar

In [ ]:
# Comparaciones

print (3 == 5)  # Imprime False ya que son distintos

print(3 != 6)  # Imprime True ya que son distintos

print(3 < 5)  # Imprime True ya que 3 es menor que 5

### Estructuras Lógicas IF

Son estructuras que, dada una o varias condiciones, permiten ejecutar secciones de códigos.

Operadores:

#### == igual a

#### != distinto de

#### < menor que

#### > mayor que

#### <= menor igual a

#### >= mayor igual a

In [ ]:
# Por ejemplo: Queremos que dado un valor de x, si este es menor a 5 imprime en
# pantalla que el valor es menor a 5, de lo contrario imprime que es mayor a 5

x = 3

if x <= 5: # Si x es menor igual a 5 entra en esta parte del codigo
  print('El valor de x es menor igual a 5')
else: # de lo contrario entra en esta parte del codigo
  print('El valor de x es mayor a 5')

### Podemos agregar mas de una condicion:

In [ ]:
x = 50

if x <= 0: # Si x es menor igual a 0 entra en esta parte del codigo
  print('El valor de x es menor igual a 0')
elif 0 < x <= 10: # Si x es mayor que 0 pero menor igual a 10 entra en esta parte del codigo
  print('El valor de x es mayor que 0 pero menor igual a 10')
elif 10 < x <= 100: # Si x es mayor que 0 pero menor igual a 10 entra en esta parte del codigo
  print('El valor de x es mayor que 10 pero menor igual a 100')
else: # de lo contrario entra en esta parte del codigo
  print('El valor de x es mayor a 100')

### Podemos combinar lógica booleana con estructura IF

In [ ]:
condicion = True

if condicion == True:
  print('La condicion es verdadera')
else:
  print('La condicion es falsa')

In [ ]:
# Equivalentemente podemos definir el bloque IF anterior de esta manera:
if condicion:
  print('La condicion es verdadera')
else:
  print('La condicion es falsa')

### Funciones

*Las funciones se definen con la palabra clave def*

**Sintaxis**

def nombre_funcion(parametros):
    
    Cuerpo de la función
    
    return

In [ ]:
# Definimos una funcion que suma dos valores y regresa el resultado

def suma(a,b):
  c = a + b
  return c

In [ ]:
# Llamamos a la función suma

suma(3,4)

In [ ]:
# Podemos definir una función con valores por defecto. Es decir, valores
# que si no son especificados son tomados por defecto con un valor asignado

def suma_triple(a,b,c=0):
  d = a + b + c
  return d

In [ ]:
# Llamamos a la función suma

suma_triple(3,4) # Si no especificamos c se lo considera como c=3

In [ ]:
suma_triple(3,4,2) # Si lo especificamos lo considera con el valor que le damos de entrada

In [ ]:
lista1 = [1,2,3,4,5]
lista2 = [-1,2,-3,4,0]

# Podemos darle a una funcion otros objetos como argumentos:
# Llamamos a la función

suma(lista1,lista2)

# Como resultado obtenemos una lista concatenada

### Operadores Lógicos AND, OR, IN, NOT IN

In [ ]:
# Si queremos ejecutar un bloque de código si se cumplen dos o mas condiciones
# usamos AND, si solo queremos ejecutar si se cumple una sola condición (y las otras no)
# usamos OR

x = 5; y = 20

if x == 5 and y == 20:
  print('x es igual a 5 e y es igual a 20')
else:
  print('x es distinto de 5 o y es distinto de 20')

In [ ]:
x = 3; y = 10

if x == 5 or y == 20:
  print('x es igual a 5 o y es igual a 20')
else:
  print('x es distinto de 5 e y es distinto de 20 (simultaneamente)')

In [ ]:
# Si queremos verificar, por ejemplo, si un elemento está o no en
# una lista usamos IN y NOT IN

x_list = [0,1,2,3,4,5,6]

print(1 in x_list, -1 in x_list)

In [ ]:
# Analogamente

print(1 not in x_list, -1 not in x_list)

### <font color='red'>**Ejercicios**</font>

Dada la siguiente lista, use el indexado para obtener la palabra **Hello**

In [ ]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

Dado el siguiente diccionario, busque a través de claves y subclaves la palabra *Hello*

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

Problema Final

Suponga que ud. está conduciendo un vehículo y va demasiado rápido. De pronto, un agente de la polícia lo detiene.

Escriba una función que tome dos argumentos, la *velocidad* del vehículo y una variable *booleana* que diga si hoy es o no su cumpleaños y devuelva uno de tres posibles resultados: **no hay infracción**, **infracción leve** y **infracción grave**. Si su velocidad es de 60 km/h o menos el resultado es **No hay multa**. Si la velocidad está entre 61 y 80 km/h inclusive, el resultado es **infracción leve**. Si la velocidad es de 81 km/h o más, el resultado es **infracción grave**. Si **hoy no** es su cumpleaños el resultado es el anterior, caso contrario, si **hoy es** su cumpleaños se le permitirá un margen de 5 km/h a los límites anteriores.

## NumPy

NumPy es una biblioteca de Python ampliamente utilizada para realizar cálculos numéricos y operaciones matemáticas en matrices y arrays multidimensionales. Proporciona una gran cantidad de funciones y herramientas para trabajar con arreglos numéricos de manera eficiente, lo que lo convierte en una herramienta fundamental para la computación científica y el análisis de datos en Python. Con NumPy, puedes realizar operaciones matemáticas básicas y avanzadas, manipulación de datos, álgebra lineal, generación de números aleatorios y mucho más. Es ampliamente utilizada en disciplinas como la ciencia de datos, la ingeniería, la física, las matemáticas y otras áreas relacionadas.

In [ ]:
# Primero debemos importar numpy
import numpy as np
# En caso de no estar instalado debemos instalarla con pip install numpy

In [ ]:
# Creamos un array (o vector en este caso)
# Lo podemos hacer a partir de una lista
mi_lista = [0,1,2,3,4,5]

In [ ]:
# Convertimos la lista a array
arr = np.array(mi_lista)
arr

In [ ]:
# Cómo creamos una matriz con numpy?
# Lo podemos hacer tambien como lista
matriz_lista = [[1,2,3],[4,5,6],[7,8,9]]
matriz_lista

In [ ]:
# La convertimos a array
np.array(matriz_lista)

In [ ]:
# Podemos crear arrays de numeros ordenados y equiespaciados con la función arange
np.arange(0,10)

In [ ]:
# Con la misma función podemos indicar que queremos numeros de dos en dos
np.arange(0,11,2)

In [ ]:
# Otra manera de crear la misma matriz es
np.arange(9)

In [ ]:
# Otra manera de crear la misma matriz es
np.arange(9).reshape(3,3)

In [ ]:
# Podemos crear matrices y vectores de 0 y 1
np.zeros(5)

In [ ]:
np.zeros((3,3))

In [ ]:
np.ones(3)

In [ ]:
# Podemos crear arrays con valores equiespaciados en un dado intervalo
# Por ej. creamos un vector de 10 elementos equiespaciados entre 0 y 1
np.linspace(0,1,10)

In [ ]:
# Tambien podemos crear un vector con numeros aleatorios entre 0 y 1
np.random.rand(5)

In [ ]:
# Cómo vemos la dimensión del vector o matriz?
arr.shape

### Indexado de los array de numpy

In [ ]:
# Los array de numpy indexan desde 0
# Creemos un vector cualquiera:

vector_ejemplo = np.array([-1,0,1,2,3,4,5,6,7,8])

In [ ]:
# El primer elemento de este array es el elemento 0:
vector_ejemplo[0]

In [ ]:
# El último elemento de este array es el elemento 9:
vector_ejemplo[9]

In [ ]:
# Si no conocemos la dimensión del array podemos indicar que queremos el último elemento
# de la siguiente manera:
vector_ejemplo[-1]

In [ ]:
# Podemos seleccionar un intervalo del array
# Por ej. del elemento 2 (incluido) al 5 (excluido)
vector_ejemplo[2:5]

### Operaciones sobre arrays

In [ ]:
# Creemos dos vectores cualquiera
vector1 = np.array([0,1,2,3,4,5])
vector2 = np.array([6,7,8,9,10,11])

# Calculamos la suma
vector1+vector2

In [ ]:
# Calculamos el vector 1 elevado al cuadrado
vector1**2

In [ ]:
# Raiz cuadrada del vector 2
np.sqrt(vector2)

In [ ]:
# Minimo
np.min(vector1)

In [ ]:
# Seno trigonometrico
np.sin(vector2)

### <font color='red'>**Ejercicios**</font>

Cree un vector de numeros pares entre 10 y 80

Escriba un código que reproduzca la siguiente salida:

```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

A partir de la matriz anterior, escriba un código que reproduzca la siguiente salida:

```python
array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])
```

Obtenga el numéro 20 de la matriz

A partir de la matriz anterior, escriba un código que reproduzca la siguiente salida:

```python
array([[ 2],
       [ 7],
       [12]])
```

A partir de la matriz anterior, escriba un código que reproduzca la siguiente salida:

```python
array([21, 22, 23, 24, 25])
```

A partir de la matriz anterior, escriba un código que reproduzca la siguiente salida:

```python
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

## Pandas


La librería pandas en Python es una herramienta de manipulación y análisis de datos de alto rendimiento. Ofrece estructuras de datos flexibles y eficientes, diseñadas para facilitar la manipulación y análisis de datos en Python. Las dos estructuras de datos principales en pandas son Series y DataFrame.

*  Series: Una Serie es un objeto unidimensional similar a un array que puede
contener cualquier tipo de datos, como números enteros, flotantes, cadenas, etc. Cada elemento en una Serie tiene una etiqueta asociada, denominada índice.

*  DataFrame: Un DataFrame es una estructura de datos bidimensional similar a una tabla, que consta de filas y columnas. Puedes pensar en un DataFrame como una hoja de cálculo o una tabla SQL. Cada columna en un DataFrame es una Serie.

Además de estas estructuras de datos, pandas proporciona una amplia gama de herramientas para realizar operaciones de limpieza, transformación y análisis de datos, como filtrado, agrupamiento, pivotado, fusión, concatenación, entre otras.

Pandas es una de las herramientas más populares en el ámbito de la ciencia de datos en Python debido a su facilidad de uso y su potencia para manejar datos de forma eficiente. Es frecuentemente utilizada en tareas como manipulación de datos, limpieza de datos, análisis exploratorio, y preparación de datos para su modelado y visualización.

In [ ]:
# Primero importamos la librería pandas
import pandas as pd
# En caso de no estar instalada, se la puede instalar con pip install pandas

### Series

In [ ]:
# Creamos una serie. Lo podemos hacer con una lista.
mi_lista = [0,10,50,'Hola']
serie = pd.Series(mi_lista)
serie

In [ ]:
# Podemos cambiar el índice de nuestra serie de la siguiente manera
indices = ['a','b','c','d']
serie = pd.Series(data=mi_lista, index=indices) # o tambien pd.Series(mi_lista, indices)
serie

In [ ]:
# Tambien podemos crear una serie a partir de un array de numpy
arr = np.array([10,20,30,40,50])
serie = pd.Series(arr)
serie

In [ ]:
# Alternativamente podemos crear una serie a partir de un diccionario
mi_dict = {'a':1, 'b':2, 'c':'Hola'}
serie = pd.Series(mi_dict)
serie

### Cómo extraemos información de una serie?

In [ ]:
# PIB en U$S
serie_1 = pd.Series([301, 631.1, 1920.1, 242.6], index = ['Chile', 'Argentina','Brasil', 'Peru'])

In [ ]:
serie_1['Brasil']

### DataFrames

In [ ]:
# Podemos crear un DataFrame de la siguiente manera:
data = {'PBI':[631.1,301,1920.1,242.6],
        'Poblacion en Millones':[46.2,19.6,215.3,34],
        'Esperanza de vida':[75,79,73,72]}

# Creo DataFrame
df = pd.DataFrame(data, index=['Argentina', 'Chile', 'Brasil', 'Peru'])
df

In [ ]:
# Exploramos el DataFrame
df.info()

In [ ]:
# Qué columnas tiene?
df.columns

In [ ]:
# Exploramos el DataFrame
df.describe()

In [ ]:
# Seleccionamos una columna
df['PBI']

In [ ]:
# Podemos seleccionar dos o más columnas
df[['PBI','Esperanza de vida']]

In [ ]:
# Seleccionamos un índice con la función loc
df.loc['Argentina']

In [ ]:
# Podemos agregar una nueva columna
df['Capital'] = {'Argentina':'Buenos Aires',
                 'Chile':'Santiago de Chile',
                 'Brasil':'Brasilia',
                 'Peru':'Lima'}

df

In [ ]:
# Podemos crear una columna a partir de una operación de una ya existente
df['80% PBI'] = df['PBI']*0.8
df

In [ ]:
# Eliminamos una columna
df.drop('80% PBI', axis=1)
# con axis=1 indicamos que es una columna la que queremos eliminar

In [ ]:
# Notar que los cambios no se guardaron y la columna sigue estando
df

In [ ]:
# Para hacer que el cambio sea permanente debemos agregar inplace=True
df.drop('80% PBI', axis=1, inplace=True)
df

In [ ]:
# Chequeamos
df

In [ ]:
# De la misma manera podemos borrar un índice (fila) usando axis=0
df.drop('Peru', axis=0, inplace=True)

In [ ]:
# Comprobamos
df

In [ ]:
# Seleccionamos un índice para ver sus respectivos valores para cada columna
df.loc['Argentina']

In [ ]:
# Tambien lo podemos seleccionar utilizando el numero de indice correspondiente
df.iloc[0]

In [ ]:
# Podemos seleccionar dos o más indices
df.loc[['Argentina','Brasil']]

In [ ]:
# O tambien indices y columnas en simultaneo
df.loc[['Argentina','Brasil'],['PBI','Capital']]

In [ ]:
# Es posible seleccionar valores del DataFrame en base a una condición matemática
df['PBI']>500

In [ ]:
# y que nos retorne los valores
df[df['PBI']>500]

In [ ]:
# Filtramos solo los valores de una columna
df[df['PBI']>500] ['PBI']

In [ ]:
# Tambien es posible filtrar en base a dos condiciones. Por ejemplo:
df[ (df['PBI']>500) & (df['PBI']<800)]

In [ ]:
# Podemos cambiar el índice por alguna de las columnas del DataFrame:
df.set_index('Capital')

In [ ]:
# Notar que los cambios no se guardaron
df

In [ ]:
# Para que los cambios se guarden
df.set_index('Capital', inplace=True)

In [ ]:
# Comprobamos
df

### Datos faltantes y relleno

Qué sucede si tenemos datos faltantes?

In [ ]:
# Supongamos que tenemos el siguiente DataFrame con NaN (Not a Number)
df = pd.DataFrame({'A':[1,2,np.nan],
                   'B':[5,np.nan,np.nan],
                   'C':[1,2,3]})

df

In [ ]:
# Chequeamos si hay NaN
df.isna()

In [ ]:
# Devuelve True si hay al menos un NaN
df.isna().any().any()

In [ ]:
# Muestra la cantidad de NaN por columna
nan_count = df.isna().sum()
nan_count

In [ ]:
# Total de NaN en todo el DataFrame
total_nan = df.isna().sum().sum()
total_nan

In [ ]:
# Eliminamos filas con faltantes de datos
df.dropna(axis=0)

In [ ]:
# O eliminamos las columnas
df.dropna(axis=1)

In [ ]:
# tambien podemos reemplazar los NaN por otro valor
df.fillna(value=0)

### Operaciones sobre un DataFrame

Podemos realizar operaciones sobre DataFrames como: media, mínimo, máximo y otras (ver en la documentación de Pandas https://pandas.pydata.org/docs/reference/frame.html).

In [ ]:
# Supongamos que tenemos el siguiente DataFrame
data = {'Empresa' : ['Google','Microsoft','Google','Apple','Microsoft','Apple'],
        'Cliente' : ['Sam','Charlie','Amy','Vanessa','Sarah','Henry'],
        'Ventas'  : [200,118,330,120,330,540]}

df = pd.DataFrame(data)
df

In [ ]:
# Agrupamos según una empresa
df.groupby('Empresa')

In [ ]:
# El anterior bloque nos devuelve un objeto. Debemos aplicarle la operación que queramos, por ejemplo la media
df.groupby('Empresa')['Ventas'].mean()

In [ ]:
# Similarmente podemos calcular el mínimo
df.groupby('Empresa').min()

In [ ]:
# U obtener una descripción más completa
df.groupby('Empresa').describe()

### Unir y concatenar DataFrames

Supongamos que tenemos dos DataFrames

In [ ]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                    index=[0, 1, 2, 3])
df1

In [ ]:
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                    index=[4, 5, 6, 7])
df2

In [ ]:
# Concatenamos en dirección de las filas
pd.concat([df1,df2], axis=0)

In [ ]:
# Concatenamos en dirección de las columnas
pd.concat([df1,df2], axis=1)

### DateTime de Pandas

El módulo DateTime nos permite trabajar con series temporales en Pandas. Las principales funciones son:

1. **Conversión de Fechas**: Permite convertir strings y otros formatos en objetos de fecha y hora.

2. **Generación de Rangos de Fechas**: Facilita la creación de secuencias de fechas con especificación de inicio, fin y frecuencia.

3. **Representación de Tiempos Específicos**: Ofrece la posibilidad de trabajar con momentos concretos en el tiempo.

4. **Duraciones**: Permite representar y operar con diferencias entre fechas, lo que resulta útil para cálculos de tiempo.

5. **Acceso a Componentes de Fechas**: Proporciona acceso a atributos como año, mes, día y hora en series de fechas.

6. **Desplazamiento de Fechas**: Facilita la suma de períodos de tiempo específicos, como meses o años, a objetos de fecha.

7. **Formateo de Fechas**: Permite convertir fechas y horas a cadenas en formatos personalizados, o viceversa.

8. **Re-muestreo de Series Temporales**: Permite cambiar la frecuencia de los datos temporales, como transformar datos diarios en mensuales.

pd.to_datetime(): Convierte eficientemente una representación de cadena de una fecha en un formato de fecha real, lo cual es útil al aprovechar la vasta funcionalidad de fechas proporcionada por Pandas, como el remuestreo.

In [ ]:
pd.to_datetime(['2021-01-01', '2021-02-01'])

pd.date_range(): Genera un rango de fechas. Permite especificar el inicio, el final y la frecuencia (diaria, mensual, etc.).

In [ ]:
pd.date_range(start='2021-01-01', end='2021-01-10', freq='D')

pd.Timestamp: Representa un punto específico en el tiempo y se puede usar para crear objetos de fecha y hora.

In [ ]:
ts = pd.Timestamp('2021-01-01')
ts

pd.Timedelta: Representa una duración, la diferencia entre dos fechas. Es útil para sumar o restar tiempo a un objeto Timestamp.

In [ ]:
td = pd.Timedelta(days=1)
td

Ejemplo de uso de Timedelta

In [ ]:
ts + td

Acceso a atributos de fecha: Una vez que tienes una serie de fechas, puedes acceder a atributos como el año, mes, día, hora, minuto, etc.

In [ ]:
dates = pd.Series(pd.date_range('2021-01-01', periods=3))
dates

In [ ]:
dates.dt.year  # Extrae el año

In [ ]:
dates.dt.day  # Extrae el mes

strftime: Se utiliza para formatear objetos de fecha y hora a cadenas en un formato específico.

In [ ]:
fecha = pd.Timestamp('2024-10-07')
formato = fecha.strftime('%d-%m-%Y')  # Resultado: '07-10-2024'
formato

In [ ]:
str_fecha = '07-10-2024 22'
fecha = pd.to_datetime(str_fecha, format='%d-%m-%Y %H')  # Resultado: Timestamp('2024-10-07 22:00:00')
fecha

Creamos DataFrame con numeros aleatorios e índice DateTime y agrupamos por mes y año para calcular media mensual y anual

In [ ]:
from datetime import datetime, timedelta

date_today = datetime.now()
days = pd.date_range(date_today, date_today + timedelta(90), freq='D')

data = np.random.randint(1, high=100, size=len(days))
df = pd.DataFrame({'date': days, 'column': data})
df

In [ ]:
df.groupby(df['date'].dt.month)['column'].mean()

In [ ]:
df.groupby(df['date'].dt.year)['column'].mean()

Seleccionamos un rango de fechas utilizando *df[start_date : end_date]*

In [ ]:
inicio = datetime.strptime('2024-10-10 15:00', '%Y-%m-%d %H:%M')  # Fecha inicial de los datos a analizar
fin = datetime.strptime('2024-10-15 15:00', '%Y-%m-%d %H:%M')     # Fecha final de los datos a analizar

df.set_index(['date'])[inicio:fin]

### <font color='red'>**Ejercicios**</font>

A continuación trabajaremos con una parte del Dataset Salaries de Kaggle (https://www.kaggle.com/datasets/kaggle/sf-salaries/data)


** A medida que avance en los ejercicios la dificultad irá aumentando. Es posible que para resolver algunos problemas necesite investigar en internet las distintas herramientas para lograr el resultado.

In [ ]:
# Descargamos datos de ejemplo
!wget -O Salaries.csv https://www.dropbox.com/scl/fi/ux8tkeicgc2emq6061eg7/Salaries.csv?rlkey=0x4pwhfdt1jc0tf03uvulhvrx&st=i6657aee&dl=0

Leemos el dataset

In [ ]:
sal = pd.read_csv('Salaries.csv')

Imprima el head del dataframe

Use el método info() para ver cuantas entradas hay y de qué tipo son

Calcule la media de la columna BasePay

Cuál es el mayor valor de OvertimePay?

Cuál es el trabajo de JOSEPH DRISCOLL? Nota: Use mayusculas, de otra manera obtendrá error por falta de coincidencia.

Cuál es el nombre de la persona mayor salario?

Cuál es el nombre de la persona con menor salario?

Obtenga el numéro de entradas únicas que tiene la columna JobTitle

Cuales son las 5 entradas más comunes de JobTitle?

## Matplotlib

La librería Matplotlib es una biblioteca de Python que proporciona una amplia gama de herramientas para crear visualizaciones estáticas, interactivas y animadas. Con Matplotlib, puedes generar una variedad de gráficos, como gráficos de líneas, gráficos de dispersión, histogramas, gráficos de barras, gráficos de contorno, gráficos de superficie y muchos más.

Matplotlib se puede utilizar tanto para crear gráficos simples como para producir visualizaciones complejas y personalizadas. La flexibilidad de Matplotlib permite controlar casi todos los aspectos de la apariencia de los gráficos, incluidos colores, estilos de línea, etiquetas de ejes, títulos, leyendas y más.

Además de su funcionalidad básica, Matplotlib se integra bien con otras bibliotecas de Python, como NumPy y Pandas, lo que facilita la visualización de datos almacenados en estructuras de datos comunes. También es posible combinar Matplotlib con herramientas de GUI como Tkinter, PyQt o wxPython para crear aplicaciones con interfaces gráficas interactivas.

En resumen, Matplotlib es una herramienta fundamental en el ecosistema de Python para visualización de datos y trazado de gráficos, utilizada ampliamente en campos como la ciencia de datos, la ingeniería, la investigación académica y muchos otros.

In [ ]:
# Importamos la librería
import matplotlib.pyplot as plt

In [ ]:
# Creamos un vector x y una función y=f(x) para graficar
x = np.linspace(0, 10, 11)
y = x ** 2

In [ ]:
# Chequeamos los valore de x e y
print(x)
print(y)

### Grafico simple

In [ ]:
# Graficamos
plt.plot(x,y)

In [ ]:
# Podemos agregar nombres a los ejes x e y. Incluso podemos agregar título al gráfico
plt.plot(x,y)
plt.xlabel('Nombre eje x')
plt.ylabel('Nombre eje y')
plt.title('Título')
plt.show()

In [ ]:
# Podemos agregar una leyenda y cambiar el color de la curva
plt.plot(x, y, color='red', label='Curva')
plt.legend()
plt.show()

### Múltiples Gráficos

In [ ]:
# Tambien podemos hacer dos o más gráficos en una misma ventana

plt.subplot(1,2,1)
plt.plot(x, y, color='red', linestyle='--')

plt.subplot(1,2,2)
plt.plot(y, x, color='green', linestyle='dashdot')

plt.show()

In [ ]:
# Tambien podemos crear un gráfico de la siguiente manera:
# Creamos Figura
fig = plt.figure()

# Agregamos los ejes a la figura
ax = fig.add_axes([0, 0, 0.8, 0.8]) # izq, abajo, ancho, alto (van de 0 a 1)

# Graficamos en los ejes anteriores
ax.plot(x, y, 'b')
ax.set_xlabel('Eje x') # Notar el uso de set_ para colocar los nombres de los ejes y titulos
ax.set_ylabel('Eje y')
ax.set_title('Titulo')

De la forma anterior el código es un poco más complicado pero la ventaja es que ahora tenemos control completo de la ubicación de los ejes y podremos agregar facilmente más de un eje a una misma figura:

In [ ]:
# Creamos figura
fig = plt.figure()

ax1 = fig.add_axes([0.1, 0.1, 0.8, 0.8]) # eje principal
ax2 = fig.add_axes([0.2, 0.5, 0.4, 0.3]) # eje secundario

# Figura grande o principal
ax1.plot(x, y, 'b')
ax1.set_xlabel('Eje x principal')
ax1.set_ylabel('Eje y principal')
ax1.set_title('Titulo principal')

# Fgiura pequeña o secundaria
ax2.plot(y, x, 'r')
ax2.set_xlabel('Eje x secundario')
ax2.set_ylabel('Eje y secundario')
ax2.set_title('Titulo secundario')

In [ ]:
# Creamos multiples gráficos en una misma figura
fig, ax = plt.subplots(nrows=2, ncols=2)

ax[0,0].plot(x, y, 'g')
ax[0,1].plot(x, y, 'b')
ax[1,0].plot(x, y, 'r')
ax[1,1].plot(x, y, 'y')

# ax[fila, columna]

In [ ]:
# O tambien
fig, ax = plt.subplots()

ax.plot(x, x**2, 'b.-') # linea azul con puntos
ax.plot(x, x**3, 'g--') # linea verde discontinua
ax.plot(x, x**0.5, 'r-') # linea roja continua

### Estilos personalizados para graficar en matplotlib

Distintos tipos de estilos para graficar

In [ ]:
fig, ax = plt.subplots(figsize=(12,6))

# Distintos ancho de linea
ax.plot(x, x+1, color="red", linewidth=0.25)
ax.plot(x, x+2, color="red", linewidth=0.50)
ax.plot(x, x+3, color="red", linewidth=1.00)
ax.plot(x, x+4, color="red", linewidth=2.00)

# opciones para estilo de linea ‘-‘, ‘–’, ‘-.’, ‘:’, ‘steps’
ax.plot(x, x+5, color="green", lw=3, linestyle='-')
ax.plot(x, x+6, color="green", lw=3, ls='-.')
ax.plot(x, x+7, color="green", lw=3, ls=':')

# discontinuidad personalizada
line, = ax.plot(x, x+8, color="black", lw=1.50)
line.set_dashes([5, 10, 15, 10]) # formato: longitud linea, longitud espaciado, ...

# posibles opciones para marcadores: marcadores = '+', 'o', '*', 's', ',', '.', '1', '2', '3', '4', ...
ax.plot(x, x+ 9, color="blue", lw=3, ls='-', marker='+')
ax.plot(x, x+10, color="blue", lw=3, ls='--', marker='o')
ax.plot(x, x+11, color="blue", lw=3, ls='-', marker='s')
ax.plot(x, x+12, color="blue", lw=3, ls='--', marker='1')

# tamaño y color del marcador
ax.plot(x, x+13, color="purple", lw=1, ls='-', marker='o', markersize=2)
ax.plot(x, x+14, color="purple", lw=1, ls='-', marker='o', markersize=4)
ax.plot(x, x+15, color="purple", lw=1, ls='-', marker='o', markersize=8, markerfacecolor="red")
ax.plot(x, x+16, color="purple", lw=1, ls='-', marker='s', markersize=8,
        markerfacecolor="yellow", markeredgewidth=3, markeredgecolor="green")

### Otros tipos de graficos:

In [ ]:
# Scatter plot o grafico de dispersión
plt.scatter(x,y)

In [ ]:
from random import sample
# creamos un vector con 50 elementos que van de 1 a 1000
data = sample(range(1, 1000), 50)
plt.hist(data)

In [ ]:
# Grafico de caja o boxplot
plt.boxplot(data, vert=True, patch_artist=True);

### Guardado de una figura

In [ ]:
# Podemos agregar una leyenda y cambiar el color de la curva
plt.plot(x, y, color='red', label='Curva')
plt.legend()
plt.savefig('figura.png', dpi=300)
plt.show()

### <font color='red'>**Ejercicios**</font>

Cree un gráfico simple con las curvas de las funciones sin(x) y cos(x) en el intervalo [0,2$\pi$]. Incluya las leyendas para distinguir ambas curvas.

Realice el mismo gráfico anterior pero esta vez en dos paneles (uno al lado del otro). Coloque título a cada gráfico.

Guarde la figura anterior en formato png con una resolución de 200 dpi

## Actividad

El siguiente bloque de código descarga un archivo csv de ejemplo que contiene una serie temporal de la estación meteorológica Laboratorio de Hidráulica ubicada en la Ciudad Universitaria de la Universidad Nacional de Córdoba.

Aquellos items con ** pueden representar un dificultad mayor.

In [ ]:
# Descargamos los datos para trabajar
!wget -O LH_01012021-01012022.csv https://www.dropbox.com/scl/fi/uu5fvr51mkat36584xb3o/LH_01012021-01012022.csv?rlkey=mmbvwcz7b2xe0o6eh9hf8tgfr&st=mlc8e2iv&dl=0

In [ ]:
# Comando de lectura de un archivo csv
df = pd.read_csv('LH_01012021-01012022.csv')
df

1. Explore el DataFrame. Cuántas columnas hay? Cuántas filas?

2. Hay NaN en el DataFrame? En caso de haber, cuántos?

3. Convierta la columna Fecha en objeto DateTime

Ayuda: Identifique el formato de la fecha

4. Calcule la media, mínimo y máximo de la columna Temperatura

5. Realice un gráfico simple de la intensidad de viento en función del tiempo

6. Reduzca el gráfico anterior y solo grafique un mes, por ejemplo agosto.

7. Calcule la media y máximo mensual de las columnas: lluvia, intensidad de viento y radiación solar

8**. Grafique la media de la radiación solar mensual, temperatura y velocidad de viento

9**. Seleccione aquellas filas que superan una temperatura de 30 grados

Ayuda:
```python
my_value = 3
my_dataframe.loc[my_dataframe["column_name"] <= my_value]
```

```python
lower_limit = 1
upper_limit = 3
my_dataframe.loc[(my_dataframe["column_name"] >= lower_limit) & (my_dataframe["column_name"] <= upper_limit)]
```

10\** \. Seleccione aquellas filas que tienen temperaturas entre 20 y 30 grados y en simultaneo vientos mayores a 20 km/h. Exporte los resultados a un archivo csv llamado *df_filtrado.csv*